FROM node:22-alpine
WORKDIR /app
ARG NPM_REGISTRY=https://registry.npmjs.org
COPY package.json package-lock.json ./
RUN npm ci --registry=$NPM_REGISTRY
COPY . .
EXPOSE 5173
CMD ["npx", "vite", "--host", "0.0.0.0"]
