export const strings = {
  title: 'Job Details',
  emptyState: 'Select a job from the list to view its details',
  loading: 'Loading details...',
  failedToLoad: 'Failed to load job details',
  statusLabel: 'Status',
  progressLabel: 'Progress',
  createdLabel: 'Created',
  lastUpdatedLabel: 'Last Updated',
  cancelJob: 'Cancel Job',
  cancelling: 'Cancelling...',
  cancel: 'Cancel',
  cancelJobAriaLabel: 'Cancel job',
  urlsLabel: 'URLs',
  totalLabel: 'total',
  httpPrefix: 'HTTP ',
  durationPrefix: 'Duration: ',
  startPrefix: 'Start: ',
  endPrefix: 'End: ',
  errorPrefix: 'Error: ',
  cancelErrorPrefix: 'Cancel error: ',
} as const;
